apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-tst6
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
          - cluster: stage
          - cluster: prod
      - list:
          elements:
          - project: tst6
  template:
    metadata:
      name: 'guestbook-{{project}}-{{cluster}}'
      labels:
        project-cleanup: "true"
    spec:
      project: '{{project}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/noahburrell0/argocd-project-tst6.git
        targetRevision: HEAD
        path: configs/guestbook/env/{{cluster}}
      destination:
        name: '{{cluster}}'
        namespace: 'guestbook-{{project}}'

